FROM node:12

# set working directory
WORKDIR /app

RUN yarn global add @vue/cli

# install and cache app dependencies
COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

#install dependencies
RUN yarn install
